# Generated by Django 4.0.6 on 2022-10-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0018_remove_customer_c_id_remove_dealer_d_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phn_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='phn_no',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phn_no',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phn_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='qty',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.BigIntegerField(),
        ),
    ]
